[[headers]]
  for = "/www/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/wwww/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/www/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
